In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('co2_emissions (1).csv',sep=';')
df.sample(5)

make                      model   vehicle_class  engine_size  \
3029        MINI         COOPER CONVERTIBLE     MINICOMPACT          1.5   
3779         GMC               YUKON XL 4WD  SUV - STANDARD          5.3   
4352       VOLVO                 S60 T6 AWD         COMPACT          2.0   
6755       DODGE  Challenger Widebody (MDS)        MID-SIZE          6.4   
1927  MITSUBISHI                     LANCER         COMPACT          2.0   

      cylinders transmission fuel_type  fuel_consumption_city  \
3029          3           AS         Z                    8.7   
3779          8            A         X                   15.4   
4352          4           AS         Z                   10.9   
6755          8            A         Z                   15.8   
1927          4            M         X                    9.6   

      fuel_consumption_hwy  fuel_consumption_comb(l/100km)  \
3029                   6.6                             7.7   
3779                  10.8                            13.3   
4352                   7.7                             9.5   
6755                   9.6                            13.0   
1927                   6.9                             8.4   

      fuel_consumption_comb(mpg)  co2_emissions  
3029                          37            181  
3779                          21            312  
4352                          30            221  
6755                          22            305  
1927                          34            193

In [24]:
df['fuel_consumption_comb(l/100km)'].max()

26.1

In [19]:
c=df. .unique()
c

array(['Z', 'D', 'X', 'E', 'N'], dtype=object)

In [20]:
c.sort()

In [22]:
print(c)

['D' 'E' 'N' 'X' 'Z']


In [12]:
df.cylinders.min()

3

In [13]:
df.cylinders.max()

16

In [2]:
i1 ='GMC'

In [3]:
dfn = df[(df['make'] == i1)]

In [4]:
b=dfn.model.unique()


In [5]:
b.sort()

In [6]:
i2 ='ACADIA'

In [7]:
dfn1 = dfn[dfn['model']==i2]

In [8]:
c = dfn1['vehicle_class'].unique()
c

array(['SUV - STANDARD'], dtype=object)

In [9]:
i3='SUV - STANDARD'

In [10]:
dfn2=dfn1[dfn1['vehicle_class']==i3]
d=dfn2['engine_size'].unique()
d

array([3.6, 2.5])

In [11]:
d.sort()

In [12]:
d

array([2.5, 3.6])

In [13]:
i4=2.5

In [14]:
dfn3=dfn2[dfn2['engine_size']==i4]
e=dfn2['cylinders'].unique()
e.sort()
e

array([4, 6], dtype=int64)

In [15]:
i5=4

In [16]:
dfn4 = dfn3[dfn3['cylinders']==i5]
f=dfn3['transmission'].unique()
f

array(['A'], dtype=object)

In [18]:
i6 = 'A'

In [19]:
dfn5 = dfn4[dfn4['transmission'] == i6]
i = dfn4['fuel_type'].unique()
i

array(['X'], dtype=object)

In [20]:
df['fuel_consumption_comb(l/100km)'].min()

4.1

In [21]:
df['fuel_consumption_comb(l/100km)'].max()

26.1