In [16]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/91775/DATA SCIENCE/projects/CO2 Emission/Data/co2_emissions (1).csv", sep=';')
df.sample(5)

make               model            vehicle_class  engine_size  \
3699       FORD              FUSION                 MID-SIZE          2.5   
7226     NISSAN          Armada 4WD           SUV - STANDARD          5.6   
3533  CHEVROLET           SILVERADO  PICKUP TRUCK - STANDARD          5.3   
4537   CADILLAC             CTS AWD                 MID-SIZE          3.6   
6583        BMW  750Li xDrive Sedan                FULL-SIZE          4.4   

      cylinders transmission fuel_type  fuel_consumption_city  \
3699          4            A         X                   11.3   
7226          8           AS         X                   17.5   
3533          8            A         X                   15.2   
4537          6           AS         X                   12.1   
6583          8           AS         Z                   14.5   

      fuel_consumption_hwy  fuel_consumption_comb(l/100km)  \
3699                   7.5                             9.6   
7226                  12.9                            15.4   
3533                  10.7                            13.1   
4537                   8.6                            10.5   
6583                   9.9                            12.4   

      fuel_consumption_comb(mpg)  co2_emissions  
3699                          29            224  
7226                          18            362  
3533                          22            309  
4537                          27            247  
6583                          23            290

In [24]:
milege = 25

In [25]:
i6 = 100/milege

In [26]:
i6

4.0

In [19]:
###
fuel_consumption_comb = 100 / milege


In [30]:
milege = 11.764705882352942
fuel_consumption_comb = abs(100/milege)
fuel_consumption_comb

8.5

In [15]:
fuel_consumption_comb = 100 / 6.024096385542168
fuel_consumption_comb

16.6

In [32]:
milege = 100/15.4
milege

6.4935064935064934

In [18]:
fuel_consumption_comb = 100 / 8.064516129032258
fuel_consumption_comb

12.4

In [ ]:
c.sort()

In [22]:
print(c)

['D' 'E' 'N' 'X' 'Z']


In [12]:
df.cylinders.min()

3

In [13]:
df.cylinders.max()

16

In [2]:
i1 ='GMC'

In [3]:
dfn = df[(df['make'] == i1)]

In [4]:
b=dfn.model.unique()


In [5]:
b.sort()

In [6]:
i2 ='ACADIA'

In [7]:
dfn1 = dfn[dfn['model']==i2]

In [8]:
c = dfn1['vehicle_class'].unique()
c

array(['SUV - STANDARD'], dtype=object)

In [9]:
i3='SUV - STANDARD'

In [10]:
dfn2=dfn1[dfn1['vehicle_class']==i3]
d=dfn2['engine_size'].unique()
d

array([3.6, 2.5])

In [11]:
d.sort()

In [12]:
d

array([2.5, 3.6])

In [13]:
i4=2.5

In [14]:
dfn3=dfn2[dfn2['engine_size']==i4]
e=dfn2['cylinders'].unique()
e.sort()
e

array([4, 6], dtype=int64)

In [15]:
i5=4

In [16]:
dfn4 = dfn3[dfn3['cylinders']==i5]
f=dfn3['transmission'].unique()
f

array(['A'], dtype=object)

In [18]:
i6 = 'A'

In [19]:
dfn5 = dfn4[dfn4['transmission'] == i6]
i = dfn4['fuel_type'].unique()
i

array(['X'], dtype=object)

In [20]:
df['fuel_consumption_comb(l/100km)'].min()

4.1

In [21]:
df['fuel_consumption_comb(l/100km)'].max()

26.1